movie_lens_dbt_pipeline:  # Must match "profile" in dbt_project.yml
  outputs:
    dev:
      dataset: movie_lens_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service_account.json 
      location: US
      method: service-account
      priority: interactive
      project: terraform-basics-458014
      threads: 4
      type: bigquery

    prod:
      dataset: prod_movie_lens_dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/local/airflow/include/gcp/service_account.json 
      location: US
      method: service-account
      priority: interactive
      project: terraform-basics-458014
      threads: 4
      type: bigquery

  target: prod