version: 2

models:
    - name: dim_movies_genres
      description: >
        unnested movie genres 
      columns:
        - name: movie_id 
          tests:
            - not_null
            - relationships:
                to: ref('stg_movies')
                field: movie_id
        - name: genre
          tests:
            - not_null    
                   
    - name: dim_users
      description: >
        Dimension table for users, enriched with city, state, and county information from zip codes.
      columns:
        - name: user_id
          description: Primary key of the user.
          tests:
            - not_null
            - unique
        - name: gender
          description: Gender of the user.

        - name: age
          description: Age bucket of the user.

        - name: occupation
          description: Occupation ID of the user.

        - name: zip_code
          description: ZIP code provided by the user.

        - name: city
          description: City mapped from ZIP code.
          tests:
            - accepted_values:
                values: ['New York', 'Los Angeles', 'Chicago']  # optional

        - name: state_id
          description: State code from ZIP code.

        - name: state_name
          description: Full state name.

        - name: county_name
          description: County from ZIP code.